#+TITLE: Implementing distributed prefill and decode stages for an LLM

* Introduction

The process of inference from an LLM can be split into two stages -
prefill and decode. The prefill stage of inference takes as its input
the entire input token stream and generates as its output a Key-Value
(KV) cache. As a result, it is computation-intensive and best
implemented on a GPU. The decode stage takes as its input the KV cache
and generates as its output the next token. By running the decode
stage several times, the full output token stream is generated. Since
the KV cache is large, the decode stage is memory bandwidth-intensive.

In some use cases, we may need to run the prefill stage on one
processor node (node 1) which handles matrix multiplication well and
the decode stage on another node (node 2) that handles memory
transfers well. This involves efficiently transferring the KV cache
from node 1 to node 2.

The goal of our prototype is to demonstrate a working setup where the
prefill stage is implemented on a GPU (node 1), the KV cache is
transmitted to a lower-capability GPU or a CPU node (node 2), and the
decode stage is implemented on node 2.

* Limitations of vLLM

The vLLM software package supports benchmarking an LLM inference and
splitting the benchmark results between the prefill and decode
stages. However, as of Feb 2026, it does not support running the
prefill and decode stages on generic separate nodes.

It only supports a specific use case where all the nodes are Nvidia
GPU nodes. Under the hood, it supports this feature by enabling
transfers of the KV cache between nodes using the [[https://developer.nvidia.com/blog/introducing-nvidia-dynamo-a-low-latency-distributed-inference-framework-for-scaling-reasoning-ai-models/][Nvidia Inference
Transfer Library]] (NIXL). This is clearly not reusable for other
GPUs.

* Recommendation on next steps

We could implement the next steps in parallel workstreams.

In the first workstream, we can ignore the problem of real-time
transfer of the KV cache. Instead, we will implement just the prefill
stage in node 1, save the resultant KV cache to disk storage for node
1, and transfer it to the disk storage for node 2. We will then
implement the decode steps in node 2 using the KV cache. We will
validate that the resulting output matches the output generated by the
entire inference process running on node 1.

The challenges we need to solve in this workstream are:
1. What software infrastructure should we use to run just the decode
   part on node 2? The potential candidates are vLLM, native PyTorch,
   and ollama.
2. How will that software infrastructure accept a KV cache that is
   created in vLLM's native format?

In the second workstream, we will look at alternatives like [[https://github.com/llm-d][llm-d]]. The
stated goal of llm-d is to be a "Kubernetes-native high-performance
distributed LLM inference framework." Further, it provides validated
recipes for running distributed prefill and decode on generic
nodes. Under the hood, llm-d uses vLLM as its inference serving
engine, so we can expect a good amount of carry-over of vLLM scripts.

The challenges we need to solve in this workstream are:
1. Can llm-d be run on a setup of just two GPUs, each from a different
   manufacturer?

* References

- [[https://www.youtube.com/watch?v=FPr37jCOvrA][Youtube video on disaggregated prefill in vLLM]]
- [[https://llm-d.ai/docs/guide/Installation/prerequisites#llm-d-infrastructure][Accelerators supported by llm-d]]
