#+TITLE: Implementing distributed prefill and decode stages for an LLM

* Introduction

The process of inference by an LLM can be split into two stages -
prefill and decode. The prefill stage of inference takes as its input
the entire input token stream and generates as its output a Key-Value
(KV) cache. As a result, it is computation-intensive and best
implemented on a high-compute GPU. The decode stage takes as its input
the KV cache and generates as its output the next token. By running
the decode stage several times, the full output token stream is generated. Since
the KV cache is large, the decode stage is memory bandwidth-intensive.

In some use cases, we may need to run the prefill stage on one
processor node (node 1) which handles matrix multiplication well and
the decode stage on another node (node 2) that handles memory
transfers well. This involves efficiently transferring the KV cache
from node 1 to node 2.


* Goal of the prototype

The ultimate goal of this prototype is to demonstrate a working setup
where the prefill stage is implemented on one GPU (node 1), the KV
cache is transmitted to a second GPU (node 2), and the
decode stage is implemented on node 2.

We plan to accomplish this ultimate goal through the following
intermediate steps.

- Step 0 :: Run aggregated inference on an Nvidia GPU
- Step 1 :: Split across two processes on the same GPU
  Demonstrate that prefill can be implemented in one process on a GPU,
  the KV cache can be saved, and the decode can be implemented on a
  second process on the same GPU.
- Step 2 :: Split across two GPUs on the same machine
  Run the decode step on a different GPU on the same
  machine. This demo will be run on a machine that has two GPUs from
  two vendors on a single machine. The KV cache can be communicated
  through PCIe or other means.
- Step 3 :: Split across two GPUs on two different machines
  Run the decode step on a different GPU on a different machine. The
  KV cache will need to be communicated through TCP/IP in this case.

These intermediate steps may be accomplished through any of the following
software stacks.
- PyTorch,
- vLLM, or
- [[https://github.com/llm-d][llm-d]] with vLLM as the inference engine.

In addition to demonstrating the prototype, we will also benchmark the
performance from using each of these approaches.


* Status of prototype

|----------------+--------+--------+--------+--------|
| Software stack | Step 0 | Step 1 | Step 2 | Step 3 |
|----------------+--------+--------+--------+--------|
| PyTorch        | X      |        |        |        |
| vLLM           | X      |        |        |        |
| llm-d          | X      |        |        |        |
|----------------+--------+--------+--------+--------|

"X" implies that that step is complete.


* Limitations of vLLM

The vLLM software package supports benchmarking an LLM inference and
splitting the benchmark results between the prefill and decode
stages. However, as of Feb 2026, it may not support running the
prefill and decode stages on generic separate nodes.

It only supports a specific use case where all the nodes are Nvidia
GPU nodes. Under the hood, it supports this feature by enabling
transfers of the KV cache between nodes using the [[https://developer.nvidia.com/blog/introducing-nvidia-dynamo-a-low-latency-distributed-inference-framework-for-scaling-reasoning-ai-models/][Nvidia Inference
Transfer Library]] (NIXL). This is clearly not reusable for other
GPUs.

We will need to investigate whether this is a real limitation.


* References

- [[https://www.youtube.com/watch?v=FPr37jCOvrA][Youtube video on disaggregated prefill in vLLM]]
- [[https://llm-d.ai/docs/guide/Installation/prerequisites#llm-d-infrastructure][Accelerators supported by llm-d]]
