#+TITLE: Steps for running AI eval tests

This directory has promptfoo-based tests for AI models.

The instructions below are for Linux.

* Python virtual environment setup

If you do not have Python installed already, install it as follows.
#+begin_src
  sudo apt-get install python3
#+end_src

Create a .venv directory and activate your Python virtual environment
as follows.
#+begin_src
  python3 -m venv .venv
  source .venv/bin/activate
#+end_src

The virtual environment is now activated. You should see the text
(.venv) in parentheses appear on the left of your command prompt.

You must always run this step before executing any Python scripts
in this repository, else you will encounter run-time errors.

* Python package installation

Install all the Python packages from requirements.txt as follows.
#+begin_src
  python -m pip install --upgrade pip
  pip install -r requirements.txt
#+end_src

This will install all the necessary Python packages in your virtual
environment. Due to the large number of packages, this will take some
time.

* Running vllm

Currently, this will only work in a GPU environment.

After activating your GPU virtual environment, run the following.

#+begin_src
python basic_vllm.py
#+end_src

This script will test a default LLM with some basic prompts.

* Installing llm-d

First, download the shell script to install the pre-requisites for
llm-d as follows.
#+begin_src shell
  curl -O https://raw.githubusercontent.com/llm-d/llm-d/main/guides/prereq/client-setup/install-deps.sh
  chmod 755 ./install-deps.sh && ./install-deps.sh
#+end_src

Once, the installation is completed, you should get a message "All
tools installed successfully."

Next, install minikube to run the Kubernetes cluster locally. Set it
up within a Docker environment. Note that this assumes a Linux OS, an
AMD64 CPU, and one or more Nvidia GPUs. These steps will be different
if you have a different configuration.
#+begin_src shell
  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  sudo install minikube-linux-amd64 /usr/local/bin/minikube

  # Update Docker to recognize the Nvidia GPU on the machine.
  sudo nvidia-ctk runtime configure --runtime=docker
  sudo systemctl restart docker
  sudo usermod -aG docker $USER && newgrp docker

  # Start a Minikube node
  minikube start --driver=docker --gpus all

  # Make Nvidia GPU an available resource for Kubernetes pods
  minikube addons enable nvidia-device-plugin
#+end_src

If everything went well, you should see a ready Minikube node when you run the
following command.
#+begin_src shell
  kubectl get nodes
#+end_src

Next, setup an account on huggingface.co and get an access token.

Use that token in the shell command below to create a secret in the
llm-d namespace for Kubernetes.

#+begin_src shell
  export HF_TOKEN=<your_Huggingface_token>
  export HF_TOKEN_NAME=${HF_TOKEN_NAME:-llm-d-hf-token}
  kubectle create namespace llm-d
  kubectl create secret generic ${HF_TOKEN_NAME} \
      --from-literal="HF_TOKEN=${HF_TOKEN}" \
      --namespace "llm-d" \
      --dry-run=client -o yaml | kubectl apply -f -
#+end_src

Checkout the latest release of llm-d.
#+begin_src shell
  branch=$(curl -s https://api.github.com/repos/llm-d/llm-d/releases/latest | jq -r '.tag_name')
  # Clone the repo and switch to the desired branch
  git clone https://github.com/llm-d/llm-d.git && cd llm-d && git
  checkout ${branch}
#+end_src

Run the following commands from the directory where you cloned llm-d.
These commands install the istio gateway provider.
#+begin_src shell
    curl -O https://raw.githubusercontent.com/llm-d/llm-d/main/guides/prereq/gateway-provider/install-gateway-provider-dependencies.sh
    chmod 755 ./install-gateway-provider-dependencies.sh && ./install-gateway-provider-dependencies.sh
    helmfile apply -f llm-d/guides/prereq/gateway-provider/istio.helmfile.yaml
#+end_src

If all went well, the following command should show at least one API
resource each of KIND InferencePool and InferenceObjective.
#+begin_src shell
kubectl api-resources | grep -iE "KIND|inference.networking.*k8s"
#+end_src

llm-d requires monitoring services to be set up. With the following
commands, set up Prometheus as the monitoring service.
#+begin_src shell
   kubectl apply -f
   https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
   kubectl apply -f
   https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
#+end_src

Next, we are ready to run one of the llm-d services. We will use
"Inference Scheduling" as our chosen example.

Run this command in the directory where you cloned llm-d.
#+begin_src shell
  cd guides/inference-scheduling
  kubectl apply -n llm-d
#+end_src

** Reference links

The instructions in the section above are adapted from the llm-d
[[https://llm-d.ai/docs/guide/Installation/quickstart][QuickStart guide]].

* Promptfoo installation

** Install Node.js
We use NVM (Node Version Manager) to handle Node.js versions on
Ubuntu WSL.

#+begin_src bash
# Update package list and install curl
sudo apt update && sudo apt install -y curl

# Download and install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

# Load nvm into the current session
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Install the Long Term Support (LTS) version of Node.js
nvm install --lts
#+end_src

** Install promptfoo
Next, we install promptfoo globally for CLI access.

#+begin_src bash
  # Install promptfoo globally using npm
  npm install -g promptfoo

  # Verify the installation
  promptfoo --version
#+end_src

* Ollama installation

Install Ollama and pull a model. In the example below, I pulled the 8B
Llama3 model.

#+begin_src
  sudo apt-get install zstd
  curl -fsSL https://ollama.com/install.sh | sh

  # Note that this is the 8B model (5 GB file size)
  ollama pull llama3.1:8b
#+end_src

* Running tests

Run the tests as follows.

#+begin_src
  promptfoo eval --config basic_local_llama3_tests.yaml
#+end_src

This will run the tests in the named YAML file.

* Downloading Llama model files and running sample scripts

Go to https://llama.meta.com/llama-downloads/, accept the terms,
and select the llama 3.2 1B and llama 3.1 8B models.

You will then receive an email with a
URL for each model type. You need to use this URL within 48 hours in
the following steps, else it will expire.

List the available llama models as follows.
#+begin_src
  llama model list --show-all
#+end_src

Find the model ID for your model (left-most column in the
table). Then, download the appropriate model as follows.
#+begin_src
  llama model download --source meta --model-id llama3.2-1B
#+end_src

When prompted, enter the URL that you received by email. The
process will now commence and download the requested model to your
computer. Note that the model you chose to download must be a model
that you accepted the terms for earlier. Otherwise, you will get a
download error.

Next, download the llama3.1 model.
#+begin_src
  llama model download --source meta --model-id llama3.1-8B
#+end_src

The models get downloaded to ~/.llama.

Then, run the sample llama3 chat completion script as follows.

#+begin_src
torchrun --nproc_per_node 1 llama3_sample_completion.py ~/.llama/checkpoints/Llama3.2-1B
#+end_src

* Installing huggingface CLI

Install huggingface to download models that vllm will use.
#+begin_src
curl -LsSf https://hf.co/cli/install.sh | bash
#+end_src

Next, setup an account on huggingface.co and get an access token.

Then, type the following and enter your access token when asked.
#+begin_src
hf auth login
#+end_src

Download the facebook/opt-125m model as follows.
#+begin_src
hf download --repo-type model facebook/opt-125m
#+end_src

If it is correctly downloaded, the following command will show you the model in the hf cache.
#+begin_src
hf cache scan
#+end_src
