#+TITLE: Steps for running AI eval tests

This directory has sample scripts and promptfoo-based tests for AI models.

The instructions below are for Linux.

* Setup Python virtual environment

If you do not have Python installed already, install it as follows.
#+begin_src
  sudo apt-get install python3
#+end_src

Create a .venv directory.
#+begin_src
  python3 -m venv .venv
#+end_src

Activate your Python virtual environment.
#+begin_src
  source .venv/bin/activate
#+end_src

The virtual environment is now activated. You should see the text
(.venv) in parentheses appear on the left of your command prompt.

You must run the source command each time you want to run the Python
scripts described below.

* Install Python packages

Install all the Python packages from requirements.txt as follows.
#+begin_src
  python -m pip install --upgrade pip
  pip install -r requirements.txt
#+end_src

This will install all the necessary Python packages in your virtual
environment. Due to the large number of packages, this will take some
time.

* Install Ollama

Install Ollama and pull a model. In the example below, I pulled the 8B
Llama3 model.

#+begin_src
  sudo apt-get install zstd
  curl -fsSL https://ollama.com/install.sh | sh

  # Note that this is the 8B model (5 GB file size)
  ollama pull llama3.1:8b
#+end_src

* Install Node.js
We use NVM (Node Version Manager) to handle Node.js versions on
Ubuntu WSL.

#+begin_src bash
# Download and install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

# Load nvm into the current session
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Install the Long Term Support (LTS) version of Node.js
nvm install --lts
#+end_src

* Install promptfoo
Next, we install promptfoo globally for CLI access.

#+begin_src bash
  # Install promptfoo globally using npm
  npm install -g promptfoo

  # Verify the installation
  promptfoo --version
#+end_src

* Run promptfoo tests

Run the tests as follows.

#+begin_src
  promptfoo eval --config basic_local_llama3_tests.yaml
#+end_src

This will run the tests in the named YAML file.

* Download Llama model files

Go to https://llama.meta.com/llama-downloads/, accept the terms,
and select the llama 3.2 1B and llama 3.1 8B models.

You will then receive an email with a
URL for each model type. You need to use this URL within 48 hours in
the following steps, else it will expire.

List the available llama models as follows.
#+begin_src
  llama model list --show-all
#+end_src

Find the model ID for your model (left-most column in the
table). Then, download the appropriate model as follows.
#+begin_src
  llama model download --source meta --model-id llama3.2-1B
#+end_src

When prompted, enter the URL that you received by email. The
process will now commence and download the requested model to your
computer. Note that the model you chose to download must be a model
that you accepted the terms for earlier. Otherwise, you will get a
download error.

Next, download the llama3.1 model.
#+begin_src
  llama model download --source meta --model-id llama3.1-8B
#+end_src

The models get downloaded to ~/.llama.

The license for the models can be found in the Llama Github web site.
For example, here is the link to the [[https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/LICENSE][Llama 3.1 models license]].

* Run sample Llama3 script

[[*Setup Python virtual environment][Activate Python venv]]

Run the sample llama3 chat completion script as follows.
#+begin_src
torchrun --nproc_per_node 1 llama3_sample_completion.py ~/.llama/checkpoints/Llama3.2-1B
#+end_src
